import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {" "}
        <h1>This is the home page</h1>
        <p>
          There isn&apos;t much here as it&apos;s just used to demo how routing
          works in the Next.js pages router
        </p>
        <Link href="/product/test-product">Go to a product page</Link>
      </main>
    </>
  );
}
